//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDT.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scenario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scenario()
        {
            this.Scenario11 = new HashSet<Scenario>();
            this.ScenarioActors = new HashSet<ScenarioActor>();
        }
    
        public int ID { get; set; }
        public int ID_Scenario { get; set; }
        public string Description { get; set; }
        public string InCondition { get; set; }
        public string OutCondition { get; set; }
        public int ID_UseCase { get; set; }
        public int ID_Project { get; set; }
        public string Scenario1 { get; set; }
        public bool Done { get; set; }
        public Nullable<int> ID_MainScenario { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scenario> Scenario11 { get; set; }
        public virtual Scenario Scenario2 { get; set; }
        public virtual UseCase UseCase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScenarioActor> ScenarioActors { get; set; }
    }
}
