//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDT.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int ID { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public int ID_Priority { get; set; }
        public int ID_State { get; set; }
        public int ID_User_Creator { get; set; }
        public int ID_Project { get; set; }
        public int ID_User_Executor { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
    
        public virtual PriorityTask PriorityTask { get; set; }
        public virtual Project Project { get; set; }
        public virtual StateTask StateTask { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
