//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDT.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTechnology
    {
        public int ID { get; set; }
        public int ID_User { get; set; }
        public int ID_Technology { get; set; }
    
        public virtual User User { get; set; }
        public virtual Technology Technology { get; set; }
    }
}
