//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomovaPrace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int ID { get; set; }
        public string Path { get; set; }
        public int ID_File_Type { get; set; }
        public int ID_Project { get; set; }
        public System.DateTime Date_Uploaded { get; set; }
        public int ID_User { get; set; }
        public string Name { get; set; }
        public string Length { get; set; }
    
        public virtual FileType FileType { get; set; }
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
