//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomovaPrace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int ID { get; set; }
        public int ID_UserA { get; set; }
        public int ID_UserB { get; set; }
        public bool Checked { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
