//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomovaPrace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requirement()
        {
            this.UseCaseRequirements = new HashSet<UseCaseRequirement>();
        }
    
        public int ID { get; set; }
        public string ID_Requirement { get; set; }
        public string Text { get; set; }
        public int ID_ReqType { get; set; }
        public int ID_Project { get; set; }
        public Nullable<int> ID_Category { get; set; }
        public Nullable<int> ID_Priority { get; set; }
        public Nullable<int> ID_Status { get; set; }
        public string Source { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ReqType ReqType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UseCaseRequirement> UseCaseRequirements { get; set; }
        public virtual CategoryRequirement CategoryRequirement { get; set; }
        public virtual PriorityRequirement PriorityRequirement { get; set; }
        public virtual StatusRequirement StatusRequirement { get; set; }
    }
}
