//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomovaPrace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequirementView
    {
        public string Category { get; set; }
        public string Priority { get; set; }
        public int ID_Project { get; set; }
        public string Type { get; set; }
        public string ID_Requirement { get; set; }
        public string Text { get; set; }
        public string Source { get; set; }
        public string Status { get; set; }
    }
}
